# Generated by Django 5.0.3 on 2024-09-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(default=''),
        ),
    ]
